## Importar la Librería de Numpy.
np es una convencion para abreviar numpy

In [77]:
import numpy as np

Los datos contenidos en los arrays deben ser homogeneos, los arrays son más rapidos y consumen menos memmoria que las listas.


Ejemplo:

In [78]:
a = np.array([1, 2, 3, 4, 5, 6])  # matriz de una fila
a

array([1, 2, 3, 4, 5, 6])

In [79]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # matriz de varias filas
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El array es la estructura de datos central en Numpy y se le conoce como Numpy-array. Es una cuadricula de valores que contiene informacion sobre datos.

N-array significa array N dimensional, es decir una matriz de cualquier número de dimensiones.
- 1D Vector o array unidimensional
- 2D Matriz o array bidimensional
- 3D o más Tensor


En Numpy las dimensiones son llamadas ejes (axes, axis), el ejemplo siguiente es un array de 2 axes. la primera axis tiene una longitud de 2 y la segunda axis una longitud de 3

In [80]:
sample_array_1 = np.array([[1,1,1], [2,2,2]])
sample_array_1

array([[1, 1, 1],
       [2, 2, 2]])

## Arrays Básicos

- Array simple

In [81]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

- Array de Ceros

In [82]:
# crea un array de 4 elementos (ceros)
cero_array = np.zeros(4)
cero_array

array([0., 0., 0., 0.])

- Array de unos

In [83]:
# crea un array de dos elementos (unos)
uno_array = np.ones(2)
uno_array

array([1., 1.])

- Array Empty.


empty crea un array vacío, que en realidad tiene elementos iniciales aleatorios. 

In [84]:
# crea un array con dos elementos aleatorios
empty_array = np.empty(2)
empty_array

array([1., 1.])

Crear un array a partir de un intervalo o range

In [85]:
range_array = np.arange(0, 12, 3)
range_array

array([0, 3, 6, 9])

Crear un array con valores espaciados linealmente

In [86]:
# array de 5 elementos espaciados (10-0)/(5-1) = 2.5
lineal_array = np.linspace(0, 10, num = 5)
lineal_array


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Concatenar y ordenar elementos

### Ordenar

In [87]:
# Ordenar np.sort()
temp_array = np.array([2,5,3,1,4])
np.sort(temp_array)

array([1, 2, 3, 4, 5])

### Concatenar

In [88]:
# concatenar arrays np.concatenate
c1 = np.array([1, 2, 3])
c2 = np.array([-7, 5, 11])
np.concatenate((c1, c2))

array([ 1,  2,  3, -7,  5, 11])

### Tamaño y forma de los arrays

In [89]:
# arrays de 3 ejes (axes)
sample_array_2 = np.array([
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]]
])
sample_array_2


array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

#### Numero de ejes del array *sample_array.ndim*

In [90]:
# Numero de ejes del array, 3D=(filas, columnas, tubos)
sample_array_2.ndim

3

#### Numero total de elementos *sample_array.size*

In [91]:
# Numero total de elementos
sample_array_2.size

24

#### Tamaño del array *sample_array.shape*

Un array con n filas y m columnas, la forma será (n,m). El numero de ejes se puede calcular con la longitud de la tupla de forma

In [92]:
# forma del array 2D(filas, columnas) 3D(filas, columnas, tubos)
sample_array_2.shape

(3, 2, 4)

####  *.dtype*

In [93]:
# retorna el tipo de elementos del array (int16, int32, float16)
sample_array_2.dtype

dtype('int32')

#### *.itemsize*

In [94]:
# tamaño en bytes de cada elemento del array
sample_array_2.itemsize

4

El tipo de array puede ser indicado al momento que se crea, ejemplo:

In [95]:
sample_array_3 = np.array([[1, 2],[3, 4]], dtype=complex)
sample_array_3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Operaciones Basicas

#### Suma y resta

In [96]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

#### Multiplicacion

In [97]:
A = np.array([[1, 1], 
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

##### *Multiplicacion de los elementos*

In [98]:
A * B

array([[2, 0],
       [0, 4]])

##### *Producto Matricial*

In [99]:
A @ B
# o de esta forma:
A.dot(B)

array([[5, 4],
       [3, 4]])

#### Array de numeros aleatorios

In [100]:
# creacion de un generador de numeros aleatorios
rg = np.random.default_rng(1) 

a1 = np.ones((2, 3), dtype= int)
b1= rg.random((2,3))



#### Suma/Resta con los operador +=, -=

In [101]:
# suma con los operador +=
b1 -= a1
b1

array([[-0.48817838, -0.0495363 , -0.85584039],
       [-0.05135055, -0.68816855, -0.57667355]])

#### sum(), max(), min(), floor(), sort()

In [102]:
# floor redondea hacia abajo
sample_array_5 = np.floor(10 * rg.random((3,3)))
sample_array_5

array([[8., 4., 5.],
       [0., 7., 5.],
       [3., 7., 3.]])

In [103]:
# sum() suma todos los elementos del array
a = sample_array_5.sum()
# suma de cada columna
b = sample_array_5.sum(axis=0)
# suma de cada fila
c = sample_array_5.sum(axis=1)
(a, b, c)

(42.0, array([11., 18., 13.]), array([17., 12., 13.]))

In [104]:
# min() y max()
print("min: ", sample_array_5.min())
print("max: ", sample_array_5.max())

min:  0.0
max:  8.0


In [105]:
# Sort()
print(sample_array_5, "\n") # No sort array
print("Ordenar por fila")
print((np.sort(sample_array_5)),"\n") # sort array filas
print("Ordenar por columnas")
print((np.sort(sample_array_5, axis=0)), "\n") # sort array columnas
# axis=0 columnas, axis=1  filas
# se puede especificar el algoritmo de ordenamiento.
print((np.sort(sample_array_5,kind="mergesort")))

[[8. 4. 5.]
 [0. 7. 5.]
 [3. 7. 3.]] 

Ordenar por fila
[[4. 5. 8.]
 [0. 5. 7.]
 [3. 3. 7.]] 

Ordenar por columnas
[[0. 4. 3.]
 [3. 7. 5.]
 [8. 7. 5.]] 

[[4. 5. 8.]
 [0. 5. 7.]
 [3. 3. 7.]]


#### *numpy.fromfunction()*

In [106]:
# aplica una funcion al array que se genera a partir 
# de las coordenadas de la dimension del array 
# f(x,y) se aplica sobre las coordenadas x,y 
# elemento a23 --> f(x,y)= x+y --> f(2,3) = 2+3 = 5
array_from_f = np.fromfunction(lambda i, j: 10*i + j, (4,4), dtype=float)
array_from_f

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.]])

### Matriz Transpuesta ***sample_array.T***

In [107]:
array_from_f.T

array([[ 0., 10., 20., 30.],
       [ 1., 11., 21., 31.],
       [ 2., 12., 22., 32.],
       [ 3., 13., 23., 33.]])

### Aplanar un array ***sample_array.ravel()***

In [108]:
# .ravel() retorna una version Plana (1 eje 1D) de un array de 2 ejes o mas ejes
sample_array_7 = np.floor(10*rg.random((3,3)))
print(sample_array_7, "\n")
print(sample_array_7.ravel())

[[4. 1. 4.]
 [2. 2. 7.]
 [2. 4. 9.]] 

[4. 1. 4. 2. 2. 7. 2. 4. 9.]


### reshape() resize() *fijar/cambiar la dimension de un array*

In [109]:
sample_array_4 = np.arange(6)
sample_array_4

array([0, 1, 2, 3, 4, 5])

In [110]:
sample_array_4 = np.arange(6)
print("original\n", sample_array_4)
# reshape retorna una matriz modificada, no cambia la matrix original
reshape_array = sample_array_4.reshape((3,2))
print("reshape\n", reshape_array)
print("original\n", sample_array_4)
# resize retorna None, la matriz se modifica
sample_array_4.resize((3,2))
print("resize\n", sample_array_4)


original
 [0 1 2 3 4 5]
reshape
 [[0 1]
 [2 3]
 [4 5]]
original
 [0 1 2 3 4 5]
resize
 [[0 1]
 [2 3]
 [4 5]]


### Array diagonal ***numpy.eye()***

eye() retorna una matriz 2D con los elementos de la diagonal iguales a 1 y el reto igual a cero.

In [111]:
eye_array = np.eye(4)
eye_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [112]:
# se puede cambiar a una diagonal superior o 
# inferior con el parametro k
# k = 0 diagonal central
# k > 0 diagonales superiores
# k < 0 diagonales inferiores

eye_array = np.eye(4, k=1)
eye_array

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [113]:
eye_array = np.eye(4, k=-1)
eye_array

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Seleccionar, Fitrar y cambiar elementos

In [114]:
sample_array_6 = np.array([1, 2, 5, 7, 1, -3, 9, 0, 2]).reshape(3,3)
sample_array_6

array([[ 1,  2,  5],
       [ 7,  1, -3],
       [ 9,  0,  2]])

#### filtra y cambiar elementos

In [115]:
sample_array_6[sample_array_6 == 2] = 13
sample_array_6[sample_array_6 <= 1] = 0

#### selección

In [116]:
sample_array_6

array([[ 0, 13,  5],
       [ 7,  0,  0],
       [ 9,  0, 13]])

In [117]:
# selecion de los elementos a partir de la fila 1
sample_array_6[1:] 

array([[ 7,  0,  0],
       [ 9,  0, 13]])

In [118]:
sample_array_6[:,2] # selecion de los elemetos a partir de la columna 2

array([ 5,  0, 13])

### Apilamiento de arrays

In [119]:
a = np.floor(10 *rg.random((2,2)))
b = np.floor(10 *rg.random((2,2)))
print(a, "\n")
print(b, "\n")

# apilamiento vertical
print(np.vstack((a, b)), "\n")

# apilamiento horizontal
print(np.hstack((a,b)),"\n")

[[9. 7.]
 [5. 2.]] 

[[1. 9.]
 [5. 1.]] 

[[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]] 

[[9. 7. 1. 9.]
 [5. 2. 5. 1.]] 



#### Incrementar la dimension de un array ***newaxis*** 

In [120]:
from numpy import newaxis
a = np.arange(3)
print(a.ndim, a)
print( a[newaxis,:].ndim, a[newaxis,:])

1 [0 1 2]
2 [[0 1 2]]


#### Copiar arrays

In [121]:
a = np.floor(10 * rg.random((3,3)))
b = a # a y b son el mismo objeto, tienen el mismo identificador
print(a)
print("a is b", a is b)
print("id(a): ", id(a), "id(b): ",id(b))

# copiar con view

# a y c tienen la misma data pero son arrays diferentes
# cambios en el array original afectan el array view
c = a.view() 
print("a is c ", a is c) 
print("id(a): ", id(a), "id(c): ",id(c))

a[0]= -7
print("a\n", a)
print("c\n", c)

# copiar con copy
# retorna un array diferente el cual no se ve afectado por cambios
# al array original
d =a.copy()
print(a is d) 
print("id(a): ", id(a), "id(d): ",id(d))
print(d)

[[6. 7. 6.]
 [9. 0. 5.]
 [4. 0. 6.]]
a is b True
id(a):  146802128 id(b):  146802128
a is c  False
id(a):  146802128 id(c):  146801456
a
 [[-7. -7. -7.]
 [ 9.  0.  5.]
 [ 4.  0.  6.]]
c
 [[-7. -7. -7.]
 [ 9.  0.  5.]
 [ 4.  0.  6.]]
False
id(a):  146802128 id(d):  139611472
[[-7. -7. -7.]
 [ 9.  0.  5.]
 [ 4.  0.  6.]]
