## Importar la Librería de Numpy.
np es una convencion para abreviar numpy

In [2]:
import numpy as np

Los datos contenidos en los arrays deben ser homogeneos, los arrays son más rapidos y consumen menos memmoria que las listas.


Ejemplo:

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])  # matriz de una fila
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # matriz de varias filas
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El array es la estructura de datos central en Numpy y se le conoce como Numpy-array. Es una cuadricula de valores que contiene informacion sobre datos.

N-array significa array N dimensional, es decir una matriz de cualquier número de dimensiones.
- 1D Vector o array unidimensional
- 2D Matriz o array bidimensional
- 3D o más Tensor


En Numpy las dimensiones son llamadas ejes (axes, axis), el ejemplo siguiente es un array de 2 axes. la primera axis tiene una longitud de 2 y la segunda axis una longitud de 3

In [24]:
sample_array_1 = np.array([[1,1,1], [2,2,2]])
sample_array_1

array([[1, 1, 1],
       [2, 2, 2]])

## Arrays Básicos

- Array simple

In [5]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

- Array de Ceros

In [7]:
# crea un array de 4 elementos (ceros)
cero_array = np.zeros(4)
cero_array

array([0., 0., 0., 0.])

- Array de unos

In [8]:
# crea un array de dos elementos (unos)
uno_array = np.ones(2)
uno_array

array([1., 1.])

- Array Empty.


empty crea un array vacío, que en realidad tiene elementos iniciales aleatorios. 

In [14]:
# crea un array con dos elementos aleatorios
empty_array = np.empty(2)
empty_array

array([1., 1.])

Crear un array a partir de un intervalo o range

In [17]:
range_array = np.arange(0, 12, 3)
range_array

array([0, 3, 6, 9])

Crear un array con valores espaciados linealmente

In [18]:
# array de 5 elementos espaciados (10-0)/(5-1) = 2.5
lineal_array = np.linspace(0, 10, num = 5)
lineal_array


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Concatenar y ordenar elementos

### Ordenar

In [20]:
# Ordenar np.sort()
temp_array = np.array([2,5,3,1,4])
np.sort(temp_array)

array([1, 2, 3, 4, 5])

### Concatenar

In [22]:
# concatenar arrays np.concatenate
c1 = np.array([1, 2, 3])
c2 = np.array([-7, 5, 11])
np.concatenate((c1, c2))

array([ 1,  2,  3, -7,  5, 11])

### Tamaño y forma de los arrays

In [32]:
# arrays de 3 ejes (axes)
sample_array_2 = np.array([
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]]
])
sample_array_2


array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

#### Numero de dimensiones del array

In [31]:
# Numero de dimensiones del array
sample_array_2.ndim

3

#### Numero total de elementos

In [33]:
# Numero total de elementos
sample_array_2.size

24

#### Forma del array

In [50]:
# forma del array
sample_array_2.shape

(3, 2, 4)