## Importar la Librería de Numpy.
np es una convencion para abreviar numpy

In [2]:
import numpy as np

Los datos contenidos en los arrays deben ser homogeneos, los arrays son más rapidos y consumen menos memmoria que las listas.


Ejemplo:

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])  # matriz de una fila
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # matriz de varias filas
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El array es la estructura de datos central en Numpy y se le conoce como Numpy-array. Es una cuadricula de valores que contiene informacion sobre datos.

N-array significa array N dimensional, es decir una matriz de cualquier número de dimensiones.
- 1D Vector o array unidimensional
- 2D Matriz o array bidimensional
- 3D o más Tensor


En Numpy las dimensiones son llamadas ejes (axes, axis), el ejemplo siguiente es un array de 2 axes. la primera axis tiene una longitud de 2 y la segunda axis una longitud de 3

In [5]:
sample_array_1 = np.array([[1,1,1], [2,2,2]])
sample_array_1

array([[1, 1, 1],
       [2, 2, 2]])

## Arrays Básicos

- Array simple

In [6]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

- Array de Ceros

In [7]:
# crea un array de 4 elementos (ceros)
cero_array = np.zeros(4)
cero_array

array([0., 0., 0., 0.])

- Array de unos

In [8]:
# crea un array de dos elementos (unos)
uno_array = np.ones(2)
uno_array

array([1., 1.])

- Array Empty.


empty crea un array vacío, que en realidad tiene elementos iniciales aleatorios. 

In [9]:
# crea un array con dos elementos aleatorios
empty_array = np.empty(2)
empty_array

array([1., 1.])

Crear un array a partir de un intervalo o range

In [10]:
range_array = np.arange(0, 12, 3)
range_array

array([0, 3, 6, 9])

Crear un array con valores espaciados linealmente

In [11]:
# array de 5 elementos espaciados (10-0)/(5-1) = 2.5
lineal_array = np.linspace(0, 10, num = 5)
lineal_array


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Concatenar y ordenar elementos

### Ordenar

In [12]:
# Ordenar np.sort()
temp_array = np.array([2,5,3,1,4])
np.sort(temp_array)

array([1, 2, 3, 4, 5])

### Concatenar

In [13]:
# concatenar arrays np.concatenate
c1 = np.array([1, 2, 3])
c2 = np.array([-7, 5, 11])
np.concatenate((c1, c2))

array([ 1,  2,  3, -7,  5, 11])

### Tamaño y forma de los arrays

In [14]:
# arrays de 3 ejes (axes)
sample_array_2 = np.array([
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]]
])
sample_array_2


array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

#### Numero de ejes del array *sample_array.ndim*

In [15]:
# Numero de ejes del array, 3D=(filas, columnas, tubos)
sample_array_2.ndim

3

#### Numero total de elementos *sample_array.size*

In [16]:
# Numero total de elementos
sample_array_2.size

24

#### Tamaño del array *sample_array.shape*

Un array con n filas y m columnas, la forma será (n,m). El numero de ejes se puede calcular con la longitud de la tupla de forma

In [17]:
# forma del array 2D(filas, columnas) 3D(filas, columnas, tubos)
sample_array_2.shape

(3, 2, 4)

####  *.dtype*

In [18]:
# retorna el tipo de elementos del array (int16, int32, float16)
sample_array_2.dtype

dtype('int32')

#### *.itemsize*

In [19]:
# tamaño en bytes de cada elemento del array
sample_array_2.itemsize

4

El tipo de array puede ser indicado al momento que se crea, ejemplo:

In [22]:
sample_array_3 = np.array([[1, 2],[3, 4]], dtype=complex)
sample_array_3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#### Reshape *fijar/cambiar la dimension de un array*

In [47]:
sample_array_4 = np.arange(6)
sample_array_4

array([0, 1, 2, 3, 4, 5])

In [48]:
sample_array_4 = sample_array_4.reshape((3,2))
sample_array_4

array([[0, 1],
       [2, 3],
       [4, 5]])

### Operaciones Basicas

#### Suma y resta

In [26]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

#### Multiplicacion

In [24]:
A = np.array([[1, 1], 
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

##### *Multiplicacion de los elementos*

In [27]:
A * B

array([[2, 0],
       [0, 4]])

##### *Producto Matricial*

In [29]:
A @ B
# o de esta forma:
A.dot(B)

array([[5, 4],
       [3, 4]])

#### Array de numeros aleatorios

In [41]:
# creacion de un generador de numeros aleatorios
rg = np.random.default_rng(1) 

a1 = np.ones((2, 3), dtype= int)
b1= rg.random((2,3))



array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

#### Suma/Resta con los operador +=, -=

In [44]:
# suma con los operador +=
b1 -= a1
b1

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

#### sum(), max() y min()

In [50]:
sample_array_5 = np.arange(9).reshape((3,3))
sample_array_5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
# sum() suma todos los elementos del array
a = sample_array_5.sum()
# suma de cada columna
b = sample_array_5.sum(axis=0)
# suma de cada fila
c = sample_array_5.sum(axis=1)
(a, b, c)

(36, array([ 9, 12, 15]), array([ 3, 12, 21]))

In [52]:
# min()
sample_array_5.min()

0

In [53]:
# max()
sample_array_5.max()

8

#### *numpy.fromfunction()*

In [74]:
# aplica una funcion al array que se genera a partir 
# de las coordenadas de la dimension del array 
# f(x,y) se aplica sobre las coordenadas x,y 
# elemento a23 --> f(x,y)= x+y --> f(2,3) = 2+3 = 5
array_from_f = np.fromfunction(lambda i, j: 10*i + j, (4,4), dtype=float)
array_from_f

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.]])

### Matriz Transpuesta ***sample_array.T***

In [75]:
array_from_f.T

array([[ 0., 10., 20., 30.],
       [ 1., 11., 21., 31.],
       [ 2., 12., 22., 32.],
       [ 3., 13., 23., 33.]])